Update index.ts
These 2 should swap around so that the last one is a terminating link. I was seeing below error.

```bash
invariant.ts:42 Error: You are calling concat on a terminating link, which will have no effect
    at new LinkError (ApolloLink.ts:31:1)```

See details https://stackoverflow.com/a/58736777